services:
  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    command: /opt/spark/bin/spark-submit main.py
    tty: true
    stdin_open: true