services:
  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8888:8888"  # Expose Jupyter port
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''
    tty: true
    stdin_open: true